on:
  push:
    branches:
      - main
  pull_request:

name: Testing

jobs:
  nix-tests:
    name: "Linux Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["ubuntu:16.04", "centos:7"]
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Run script
        run: |
          echo 'uname'
          uname -a
          echo 'lscpu'
          lscpu
          echo 'lsblk'
          lsblk -a
          echo 'os-release'
          cat /etc/os-release
          echo 'cgroup'
          cat /proc/1/cgroup
